-- note Change data type of column in table

SELECT * FROM EMPLOYEE;

CREATE TABLE EMPLOYEE_CLONE AS SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE_CLONE;

DROP TABLE EMPLOYEE_CLONE;

DESCRIBE EMPLOYEE;

CREATE TABLE EMPLOYEE_CLONE AS (SELECT CAST(EMPNO) AS VARCHAR2, EMPNAME, SALARY, DEPTNO FROM EMPLOYEE);

DESCRIBE EMPLOYEE_CLONE;

DECLARE
  TYPE my_emp_cur_type IS REF CURSOR;
  my_emp_cur my_emp_cur_type;
  CREATE OR REPLACE PROCEDURE P_GET_EMP_CUR (CUR_EMP OUT my_emp_cur_type)
  IS
    BEGIN
      OPEN CUR_EMP FOR SELECT * FROM EMPLOYEE;
    END;
  /
BEGIN
  NULL;
END;



